import {
  mkdirSync,
  existsSync,
  writeFileSync,
  readFileSync,
  chmodSync,
} from 'node:fs';
import { join } from 'node:path';

export interface GenerateCodexArgs {
  token: string;
  apiUrl: string;
  cwd: string;
  force?: boolean;
  yes?: boolean;
  confirm?: (prompt: string) => Promise<boolean>;
}

const GITIGNORE_ENTRY = '.codex/config.toml';

export async function generateCodex(args: GenerateCodexArgs): Promise<void> {
  const codexDir = join(args.cwd, '.codex');
  const configPath = join(codexDir, 'config.toml');
  const force = args.force ?? false;
  const yes = args.yes ?? false;
  const confirm = args.confirm ?? defaultConfirm;

  if (existsSync(configPath) && !force) {
    // SEC-4-B mirror: do NOT read or echo file contents — file holds literal
    // Authorization Bearer <PAT> in http_headers; echo would land in stdout.
    console.log('.codex/config.toml already exists; pass --force to overwrite.');
    if (!yes) {
      const ok = await confirm(
        `Overwrite .codex/config.toml with new PAT-backed convo MCP server config? [y/N] `,
      );
      if (!ok) {
        console.log('Aborted.');
        return;
      }
    }
  }

  if (!existsSync(codexDir)) {
    mkdirSync(codexDir, { recursive: true, mode: 0o700 });
  } else {
    chmodSync(codexDir, 0o700);
  }

  // Codex MCP config (Streamable HTTP server form).
  // bearer_token_env_var alternative deferred to F-MIBHS-CODEX-ENV-VAR-HARDENING.
  const content = [
    '# Generated by `moot init --harness codex`. Do not commit (PAT inline).',
    '',
    '[mcp_servers.convo]',
    `url = "${args.apiUrl}/mcp"`,
    `http_headers = { Authorization = "Bearer ${args.token}" }`,
    '',
  ].join('\n');
  writeFileSync(configPath, content);
  chmodSync(configPath, 0o600);
  console.log(`Wrote .codex/config.toml         (chmod 600)`);

  appendGitignoreEntry(args.cwd);
}

function appendGitignoreEntry(cwd: string): void {
  const gitignorePath = join(cwd, '.gitignore');
  if (existsSync(gitignorePath)) {
    const existing = readFileSync(gitignorePath, 'utf8');
    if (existing.includes(GITIGNORE_ENTRY)) {
      return;
    }
    const sep = existing.endsWith('\n') ? '' : '\n';
    writeFileSync(
      gitignorePath,
      `${existing}${sep}${GITIGNORE_ENTRY}\n`,
    );
    console.log(`Appended '${GITIGNORE_ENTRY}' to .gitignore`);
  } else {
    writeFileSync(gitignorePath, `${GITIGNORE_ENTRY}\n`);
    console.log(`Created .gitignore with '${GITIGNORE_ENTRY}' entry`);
  }
}

async function defaultConfirm(prompt: string): Promise<boolean> {
  const { createInterface } = await import('node:readline/promises');
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const answer = (await rl.question(prompt)).trim().toLowerCase();
  rl.close();
  return answer === 'y' || answer === 'yes';
}
